### ISSUE TITLE
Web: Clear results if package is changed

### ISSUE THREAD

**Issue by mariuswinger** [equinor/mercury#140]

**Comment by ingeridhellen** [comment]
Not sure if I see the value of this.
Also, if we do agree to do this, then the results should be cleared whenever any of the input values changed, not just the package.

**Comment by mariuswinger** [comment]
This was coming from the view of switching units, since the conversion is dependent on the package used. I.e. if you switch package, the conversion from Sm3/d -> kg/d is different. But it can maybe be solved in a different way.

**Comment by soofstad** [comment]
Not doing
