### ISSUE TITLE
Zero mercury crashes page

### ISSUE THREAD

**Issue by ingeridhellen** [equinor/mercury#142]
Reproduction:
1. Create a new fluid package with demo data, except for mercury, which is set to 0
2. Run calculations with default temp and pressure

The problem seems to be that the componentFractions does not have the mercury key,. This causes PhaseTable to crash, since mole concentration and mercury flow cannot be calculated. Not sure how to best solve this though

**Comment by mariuswinger** [comment]
I think mercury is a non-optional parameter. Should ask Eleni about this.
