### ISSUE TITLE
api: Add threshold for feed normalization

### ISSUE THREAD

**Issue by ingeridhellen** [equinor/mercury#155]
When normalization was done in web, we had a threshold of 0.01 before normalizing. This is not the case now, when the normalization is handled by the api. Is this done on purpose or shoould we fix this?

**Comment by mariuswinger** [comment]
This is now handled by always normalizing and giving back the normalized values to be displayed in the MoleTable. I.e. if the ratios sum to slightly above or below 1, the values in that table will be slightly different from the input values. I think this solution should be OK? Not really sure why we used the threshold in web to begin with.

**Comment by mariuswinger** [comment]
Solution: Fix so that sum of components have more precision.
