### ISSUE TITLE
styling(fluidDialog): align component input on the right

### ISSUE THREAD

**Issue by soofstad** [equinor/mercury#163]
Also increase width of "name" input and size of "description" input

![Image](https://user-images.githubusercontent.com/11062560/198950460-712072d9-84bb-4d5c-9546-0525513ef961.png)

**Comment by ingeridhellen** [comment]
The extra space disappears if you select the components with the longest name. Having us use the entire width of the dialog always would mean we would have to fix the width of the table. But I guess that would be okay

**Comment by soofstad** [comment]
We could set a fixed width for the table, but this was a poorly worded issue. I'd say the goal is not to use the entire width, but have a longer name and description input, and have the table align right. Looks a bit messy the positioning now.
