### ISSUE TITLE
Feat(web): Order components to start with Mercury, H2S, Water, MEG, TEG, and rest....

### ISSUE THREAD

**Issue by ingeridhellen** [equinor/mercury#191]

**Comment by ingeridhellen** [comment]
@mariuswinger Order comes from the API, could you update there instead?

**Comment by mariuswinger** [comment]
Don't think so, as the order comes from the component ids, which I think is standarised? @soofstad

**Comment by soofstad** [comment]
If the order returned from the API is kept all the way (which seems to be the case), all we need to do is reorder `api/src/common/components.py`.
Should not matter if the order is standarised or not, as long as all the components are there

**Comment by mariuswinger** [comment]
Related to #201? @ingeridhellen

**Comment by ingeridhellen** [comment]
Hvis du lager en pakke med [Ethane, Water, Mercury] i den rekkefølgen, og deretter åpner dialogen på nytt for å endre den, ønsker du da at rekkefølgen skal vises slik du la den inn ([Ethane, Water, Mercury]) eller med default sorteringer ([Mercury, Water, Ethane])? Nå har vi implementert sistnevnte, og er litt jobb å endre det
