### ISSUE TITLE
Refactor: Move phase fractions to separate table (one line)

### ISSUE THREAD

**Issue by soofstad** [equinor/mercury#260]
Could create some screen shots locally and show to PO for feedback.
One suggestion is to put it above the "MoleTable"

**Comment by ingeridhellen** [comment]
Suggestions:

![Image](https://user-images.githubusercontent.com/64828956/205928956-68310799-7636-46bc-808b-1caf25db6cd6.png)

**Comment by soofstad** [comment]
Think that is fine. Perhaps a small spacer between the two tables?
Anyway ask if PO like it :)
